# Generated by Django 3.1.7 on 2021-04-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210404_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated', 'title'], 'permissions': (('manage_blog_posts', 'Manage blog posts.'),), 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
