# Generated by Django 3.1.7 on 2021-04-04 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210404_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated', 'title'], 'permissions': (('create_blog_posts', 'Collaborator can create blog posts.'), ('view_blog_posts', 'Collaborator can view blog posts.'), ('edit_blog_posts', 'Collaborator can update blog posts.'), ('delete_blog_posts', 'Collaborator can delete blog posts.')), 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='The users that collaborate on this blog post', related_name='collaborator_on_blog_post', through='blog.BlogPostCollaborator', to=settings.AUTH_USER_MODEL, verbose_name='Collaborators'),
        ),
    ]
